project:
  type: website
  output-dir: "docs"

website:
  title: "Mert Kobaş"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: linkedin
        href: www.linkedin.com
      - icon: github
        href: https://github.com/mertkobas
      - icon: twitter
        href: https://x.com/mertkobas
format:
  html:
    theme: solar
    css: styles.css

editor: visual

