project:
  type: website
  output-dir: "docs"

website:
  title: "Mert Kobaş"
  navbar:
    pinned: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Research"
        file: research/index.qmd
      - text: "CV"
        file: MertCv.pdf

format:
  html:
    theme: 
      - html/ath.scss
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    

editor: visual

