project:
  type: website
  output-dir: "docs"

website:
  title: "Mert Kobaş"
  navbar:
    pinned: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "CV"
        file: MertCv.pdf

format:
  html:
    theme: flatly
    toc: false
    grid:
      sidebar-width: 150px
      margin-width: 200px
    

editor: visual

