---
title: " Spatial language development in preterm and full-term infants: The role of object exploration and parents’ spatial input "
author: "Mert Kobaş"
date: "2025-06-28"
categories: 
pub-info:
  reference: >-
    Kobaş, M., Demir-Lira, Ö., Akman, İ., & Göksun, T. (2025). Spatial Language Development in Preterm and
    Full-Term Infants: The Role of Object Exploration and Parents’ Spatial Input. Journal of Child
    Experimental Psychology, 256, 106264.
  links:
    - name: Article
      url: https://doi.org/10.1016/j.jecp.2025.106264
      icon: fa-solid fa-scroll
doi: 10.1016/j.jecp.2025.106264
---

# Spatial language development in preterm and full-term infants: The role of object exploration and parents’ spatial input

## Highlights

-   Investigating the relation among object exploration, parents’ spatial input, and spatial language development in preterm and full-term infants.

-   Preterm and full-term groups were similar in object exploration but received different spatial input.

-   Parents’ spatial input co-occurred with object exploration events, was lower for preterm infants.

-   The interaction between object exploration and parents’ spatial input at 14 months predicted spatial language at 26 months regardless of the neonatal condition.

-   This interaction may lead to a cascading effect on spatial language development.

## Abstract

\
Infants learn object features and relations among objects by exploring them. Object exploration and parents’ verbal input related to these spatial characteristics may lead to cascades for the development of spatial language. This longitudinal study examined whether infant object exploration and parents’ spatial input at Time 1 (*M*~age~ = 13.7 months) predicted spatial language of preterm infants (mean gestational age = 30 weeks) and full-term infants (mean gestational age = 38.9 weeks) at Time 2 (*M*~age~ = 26 months). The object exploration and parents’ spatial input at Time 1 were coded from the semi-structured free play sessions, and infant spatial language was assessed via a parental report at Time 2. Our results showed no differences between preterm and full-term groups on object exploration. However, parents’ spatial input differed based on neonatal condition, in which preterm infants received less input than full-term infants. Parents’ spatial input co-occurred with 44% of the object exploration events, with a significant difference between groups (preterm: *M* = 36.1%; full-term: *M* = 52.1%). Importantly, the interaction between object exploration and parents’ spatial input at Time 1 predicted children’s spatial language knowledge at Time 2 regardless of children’s neonatal status. Infants who explored objects for longer periods and received greater spatial input from their parents at Time 1 knew more spatial words at Time 2 than infants who explored objects less and received less input at Time 1. These findings suggest that early object exploration and parents’ spatial input together can lead to a cascading effect on later spatial language development for both preterm and full-term infants.

[Click here to read this article!](https://www.sciencedirect.com/science/article/abs/pii/S0022096525000700)
